### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by theonlyfoxy**
Added Permanently Environments For Game Addons...

### CODE REVIEW

**Comment by theonlyfoxy** [comment]
its Good Thing For Improve GamePanel , Also More Functions on Addons <3

**Comment by Adjokip** [comment]
These environment variables would only be set on new installations... what about current installations?

From what I tested, the agent doesn't "see" the environment variables, so what does this do?

If an addon is needing sudo access for some reason, then I believe it would be better to edit the function in the agent which handles addon installation ([start_file_download](https://github.com/OpenGamePanel/OGP-Agent-Linux/blob/master/ogp_agent.pl#L1608))

Where it's looping over each line, add a check for a static variable (such as `%SUDOPW%`), if such condition is true, replace the static variable with `$SUDOPASSWD`

If the agent username is needed, that can also be done in the addon script.
```
AGENTUSER=$(echo %home_path% |cut -d/ -f 3)
```

**Comment by theonlyfoxy** [comment]
How About This ?
[Click Me...](https://github.com/OpenGamePanel/OGP-Agent-Linux/compare/master...FIREFOXCYBER:patch-2)

**Comment by own3mall** [comment]
I see no good reason or use for this.

**Pull request closed without merging**
