### PR TITLE
Noticed that first iteration of top also isn't acurrate...

### PR DESCRIPTION
**Pull request by Zorrototo**
...so I propose this change to have results from second iteration of top. If you have better solution please modify this PR.

### CODE REVIEW

**Comment by own3mall** [comment]
Can you please change `tail -36` to `tail -n 36` in your command?  I think that will be more compatible for older systems.

**Comment by Zorrototo** [comment]
<del>Don't accept the PR, something isn't working anymore. I need to find better way of doing that because today on my Process Monitor it does not show the second iteration of top...</del>

**Comment by Zorrototo** [comment]
Ok Found maybe a better way
`top -b -c -i -o +%CPU -w512 -n2 | awk '/^top/{i++}i==2' | grep "COMMAND" -A 30`
I added -i to top command to hide idle processes, used awk to only show second iteration of top, and grep to list max of 30 lines of result after the line containing COMMAND (what we can call the table header: ` PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND`).
Should be good like that.
Modifying PR now.

edit: yeah seems to be perfect now, I run top in a terminal and the process monitor of panel side by side, and they match each time process monitor auto refreshes.

**Comment by Zorrototo** [comment]
Screenshot of result https://www.dropbox.com/s/uwlot0bl1jmo7je/Capture%20d%27%C3%A9cran%202017-05-25%2013.26.34.png?dl=0

**Pull request merged**
